/*
 *  @author: Trịnh Thiên Long
 *  @created date:
 *  @last modified date:
 */
package boundary;

import common.Constants;
import controller.RegisterBorrowBookController;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 * @author longdragon
 */
public class BookDetailsUI extends javax.swing.JFrame {

    RegisterBorrowBookController registerBorrowBookController;

    /**
     * Creates new form BookDetailsUI
     */
    public BookDetailsUI() {
        registerBorrowBookController = new RegisterBorrowBookController();
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBookCover = new javax.swing.JLabel();
        lblBookName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiscription = new javax.swing.JTextArea();
        btnRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblIsbn = new javax.swing.JLabel();
        lblAuthors = new javax.swing.JLabel();
        lblPublisher = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblBookNumber = new javax.swing.JLabel();
        lblMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book details");
        setForeground(new java.awt.Color(254, 254, 254));
        setResizable(false);

        lblBookCover.setBackground(new java.awt.Color(168, 168, 168));
        lblBookCover.setOpaque(true);

        lblBookName.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblBookName.setForeground(new java.awt.Color(35, 51, 92));
        lblBookName.setText("Book name");

        txtDiscription.setEditable(false);
        txtDiscription.setColumns(20);
        txtDiscription.setRows(5);
        txtDiscription.setTabSize(4);
        txtDiscription.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtDiscription.setFocusable(false);
        jScrollPane2.setViewportView(txtDiscription);

        btnRegister.setBackground(new java.awt.Color(81, 154, 205));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(53, 183, 107));
        jLabel1.setText("ISBN");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(53, 183, 107));
        jLabel2.setText("Authors");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(53, 183, 107));
        jLabel3.setText("Publisher");

        lblIsbn.setForeground(new java.awt.Color(81, 154, 205));
        lblIsbn.setText("jLabel4");

        lblAuthors.setForeground(new java.awt.Color(81, 154, 205));
        lblAuthors.setText("jLabel5");

        lblPublisher.setForeground(new java.awt.Color(81, 154, 205));
        lblPublisher.setText("jLabel6");
        lblPublisher.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(53, 183, 107));
        jLabel4.setText("Book Number");

        lblBookNumber.setForeground(new java.awt.Color(81, 154, 205));
        lblBookNumber.setText("jLabel5");

        lblMsg.setForeground(new java.awt.Color(255, 0, 0));
        lblMsg.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblBookNumber))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblPublisher))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblAuthors))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblIsbn))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblBookCover, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblBookName)
                                                                .addGap(0, 236, Short.MAX_VALUE))
                                                        .addComponent(jScrollPane2)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(134, 134, 134)
                                                                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblMsg)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblBookName)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(lblBookCover, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(lblIsbn)
                                        .addComponent(lblMsg))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(lblAuthors))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(lblPublisher))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(lblBookNumber))
                                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        try {
            int status = registerBorrowBookController.register(lblBookNumber.getText());
            lblMsg.setForeground(new java.awt.Color(255, 0, 0));
            switch (status) {
                case Constants.CARDEXPIRED:
                    lblMsg.setText("Your card is expired.");
                    break;
                case Constants.OVERDUEBOOK:
                    lblMsg.setText("You have overdue unreturned books.");
                    break;
                case Constants.BOOKNOTAVAILABLE:
                    lblMsg.setText("This book is not available right now.");
                    break;
                case Constants.OVERLIMIT:
                    lblMsg.setText("Ban khong the muon qua 5 quyen sach.");
                    break;
                case Constants.BOOKREGISTERED:
                    lblMsg.setText("Khong the muon qua 1 ban copy voi moi tua sach.");
                    break;
                case Constants.REGISTERSUCCESS:
                    lblMsg.setForeground(new java.awt.Color(3, 201, 34));
                    lblMsg.setText("Successfully Registered.");
//                    call to save method in controller to save in db
                    registerBorrowBookController.save(lblBookNumber.getText());
                    break;
                default:
                    System.out.println("something wrong");
            }
            System.out.println(status);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(BookDetailsUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookDetailsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookDetailsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuthors;
    private javax.swing.JLabel lblBookCover;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblBookNumber;
    private javax.swing.JLabel lblIsbn;
    private javax.swing.JLabel lblMsg;
    private javax.swing.JLabel lblPublisher;
    private javax.swing.JTextArea txtDiscription;
    // End of variables declaration//GEN-END:variables

    /**
     * Set noi dung cho trang book details
     *
     * @param title      tieu de sach
     * @param authors    tac gia sach
     * @param isbn       ma isbn cua sach
     * @param bookNumber ma sach
     * @param publisher  nha xuat ban
     */

    public void setContent(String title, String authors, String isbn, String bookNumber, String publisher) {
        lblBookName.setText(title);
        lblAuthors.setText(authors);
        lblIsbn.setText(isbn);
        txtDiscription.setText(title + " 's discription will be written here.");
        lblBookNumber.setText(bookNumber);
        lblPublisher.setText(publisher);
    }
}
